Repository ita-social-projects/Forum, pull requests merged in 2024-04, with the labels that each got.

#498 #496 bug UI of new members
  FrontEnd/src/components/landing-page/MainPage.module.css
  FrontEnd/src/components/landing-page/about-section/About.css
  FrontEnd/src/components/landing-page/companies/Companies.jsx
  FrontEnd/src/components/landing-page/companies/Companies.module.css
  FrontEnd/src/components/landing-page/login-banner/LoginBanner.css
  FrontEnd/src/global.css
Labels: bug

#557 Added css for label in PasswordField
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.module.css
Labels: improvement

#541 #534 Improve fields validation on the Registration form and Edit profile page
  FrontEnd/src/components/ProfilePage/FormComponents/AdditionalInfo.js
  FrontEnd/src/components/ProfilePage/FormComponents/ContactsInfo.js
  FrontEnd/src/components/ProfilePage/FormComponents/DeleteProfileComponent/DeleteProfileModal.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormComponents.module.css
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/FullField.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/FullField.module.css
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.module.css
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/ImageField.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/MultipleSelectChip.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.js
  FrontEnd/src/components/ProfilePage/FormComponents/FormFields/TextField.js
  FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
  FrontEnd/src/components/ProfilePage/FormComponents/UserInfo.js
  FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js
  FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.module.css
  FrontEnd/src/constants/constants.js
  FrontEnd/src/utils/preventEnterSubmit.js
Labels: task
