Repository ita-social-projects/Forum, pull requests merged in 2025-01, with the labels that each got.

#1068 Incorrect Header Elements on Admin Page
  FrontEnd/src/components/Header/Navbar/Navbar.jsx
Labels: bug, UI

#1082 button to log in to the admin panel in the header
  FrontEnd/src/components/Header/Navbar/Profile.jsx
Labels: task, UI

#1097 #1096 [Edit Profile] Fixed bug with warning icon position in mobile version
  FrontEnd/src/pages/ProfilePage/FormComponents/FormFields/ImageField.jsx
  FrontEnd/src/pages/ProfilePage/FormComponents/FormFields/ImageField.module.css
Labels: bug
